[phases.setup]
nixPkgs = ['nodejs_20']

[phases.install]
cmds = ['npm install', 'cd frontend && npm install', 'cd backend && npm install']

[phases.build]
cmds = ['cd frontend && npm run build']

[start]
cmd = 'node -e "const fs = require(\'fs\'); if (fs.existsSync(\'./server.js\')) require(\'./server.js\'); else require(\'./backend/server.js\');"'
